package org.jet.optimizations.analysis.expressions;

import org.objectweb.asm.Opcodes;

public class YieldSizes implements Opcodes {

    public static int[] instructions = new int[1000];

    static {
        instructions[AALOAD] = 1;
        instructions[AASTORE] = 0;
        instructions[ACONST_NULL] = 1;
        instructions[ALOAD] = 1;
        instructions[ANEWARRAY] = 1;
        instructions[ARETURN] = 0;
        instructions[ARRAYLENGTH] = 1;
        instructions[ASTORE] = 0;
        instructions[ATHROW] = 1;
        instructions[BALOAD] = 1;
        instructions[BASTORE] = 0;
        instructions[BIPUSH] = 1;
        instructions[CALOAD] = 1;
        instructions[CASTORE] = 0;
        instructions[CHECKCAST] = 1;
        instructions[D2F] = 1;
        instructions[D2I] = 1;
        instructions[D2L] = 1;
        instructions[DADD] = 1;
        instructions[DALOAD] = 1;
        instructions[DASTORE] = 0;
        instructions[DCMPG] = 0;
        instructions[DCMPL] = 0;
        instructions[DCONST_0] = 1;
        instructions[DCONST_1] = 1;
        instructions[DDIV] = 1;
        instructions[DLOAD] = 1;
        instructions[DMUL] = 1;
        instructions[DNEG] = 1;
        instructions[DREM] = 1;
        instructions[DRETURN] = 0;
        instructions[DSTORE] = 0;
        instructions[DSUB] = 1;
        instructions[DUP] = 1;
        instructions[DUP_X1] = 1;
        instructions[DUP_X2] = 1;
        instructions[DUP2] = 2;
        instructions[DUP2_X1] = 2;
        instructions[DUP2_X2] = 2;
        instructions[F2D] = 1;
        instructions[F2I] = 1;
        instructions[F2L] = 1;
        instructions[FADD] = 1;
        instructions[FALOAD] = 1;
        instructions[FASTORE] = 0;
        instructions[FCMPG] = 0;
        instructions[FCMPL] = 0;
        instructions[FCONST_0] = 1;
        instructions[FCONST_1] = 1;
        instructions[FCONST_2] = 1;
        instructions[FDIV] = 1;
        instructions[FLOAD] = 1;
        instructions[FMUL] = 1;
        instructions[FNEG] = 1;
        instructions[FREM] = 1;
        instructions[FRETURN] = 0;
        instructions[FSTORE] = 0;
        instructions[FSUB] = 1;
        instructions[GETFIELD] = 1;
        instructions[GETSTATIC] = 1;
        instructions[GOTO] = 0;
        instructions[I2B] = 1;
        instructions[I2C] = 1;
        instructions[I2D] = 1;
        instructions[I2F] = 1;
        instructions[I2L] = 1;
        instructions[I2S] = 1;
        instructions[IADD] = 1;
        instructions[IALOAD] = 1;
        instructions[IAND] = 1;
        instructions[IASTORE] = 0;
        instructions[ICONST_M1] = 1;
        instructions[ICONST_0] = 1;
        instructions[ICONST_1] = 1;
        instructions[ICONST_2] = 1;
        instructions[ICONST_3] = 1;
        instructions[ICONST_4] = 1;
        instructions[ICONST_5] = 1;
        instructions[IDIV] = 1;
        instructions[IF_ACMPEQ] = 0;
        instructions[IF_ACMPNE] = 0;
        instructions[IF_ICMPEQ] = 0;
        instructions[IF_ICMPGE] = 0;
        instructions[IF_ICMPGT] = 0;
        instructions[IF_ICMPLE] = 0;
        instructions[IF_ICMPLT] = 0;
        instructions[IF_ICMPNE] = 0;
        instructions[IFEQ] = 0;
        instructions[IFGE] = 0;
        instructions[IFGT] = 0;
        instructions[IFLE] = 0;
        instructions[IFLT] = 0;
        instructions[IFNE] = 0;
        instructions[IFNONNULL] = 0;
        instructions[IFNULL] = 0;
        instructions[IINC] = 0;
        instructions[ILOAD] = 1;
        instructions[IMUL] = 1;
        instructions[INEG] = 1;
        instructions[INSTANCEOF] = 1;
        instructions[INVOKEDYNAMIC] = -1;
        instructions[INVOKESTATIC] = -1;
        instructions[INVOKEVIRTUAL] = -1;
        instructions[IOR] = 1;
        instructions[IREM] = 1;
        instructions[IRETURN] = 0;
        instructions[ISHL] = 1;
        instructions[ISHR] = 1;
        instructions[ISTORE] = 0;
        instructions[ISUB] = 1;
        instructions[IUSHR] = 1;
        instructions[IXOR] = 1;
        instructions[JSR] = 1;
        instructions[L2D] = 1;
        instructions[L2F] = 1;
        instructions[L2I] = 1;
        instructions[LADD] = 1;
        instructions[LALOAD] = 1;
        instructions[LAND] = 1;
        instructions[LASTORE] = 1;
        instructions[LCMP] = 0;
        instructions[LCONST_0] = 1;
        instructions[LCONST_1] = 1;
        instructions[LDC] = 1;
        instructions[LDIV] = 1;
        instructions[LLOAD] = 1;
        instructions[LMUL] = 1;
        instructions[LNEG] = 1;
        //instructions[LOOKUPSWITCH]
        //instructions[TABLESWITCH]
        instructions[LOR] = 1;
        instructions[LREM] = 1;
        instructions[LRETURN] = 0;
        instructions[LSHL] = 1;
        instructions[LSHR] = 1;
        instructions[LSTORE] = 0;
        instructions[LSUB] = 1;
        instructions[LUSHR] = 1;
        instructions[LXOR] = 1;
        instructions[NEW] = 1;
        instructions[NEWARRAY] = 1;
        instructions[NOP] = 0;
        instructions[POP] = 0;
        instructions[POP2] = 0;
        instructions[PUTFIELD] = 0;
        instructions[PUTSTATIC] = 0;
        instructions[RET] = 0;
        instructions[RETURN] = 0;
        instructions[SALOAD] = 1;
        instructions[SASTORE] = 0;
        instructions[SIPUSH] = 1;
        instructions[SWAP] = 2;
        //instructions[TABLESWITCH]

    }


}
